### ISSUE TITLE
Save picture of map

### ISSUE THREAD

**Issue by fjulle** [KeeganW/ti4#61]
If possible, being able to generate a picture of the map would be great :-)

Again: Great great program! Thx!

**Comment by KeeganW** [comment]
Thanks for your feedback! Out of curiosity, what would be the purpose of this @fjulle? 

For now, you can screenshot the tiles, or copy the url to share digitally. One other possible enhancement could be to improve the print version of the page (when you attempt to print the page) so that it clearly shows the tiles/number overlays.

**Comment by fjulle** [comment]
Hey

The print idea sound cool. 

The purpose would be for easy sharing through different medias, but ill try the digital way! Thanks!

**Comment by KeeganW** [comment]
@fjulle I scrapped the print idea, and added the download image option. After generating a map, you can click on the "Share This Map" button, then on "Download Map Image" to get a png of the map. It can have tile number overlays and scales to the size that is being displayed on the application. Here is an example of one I generated.
![ti4-map](https://user-images.githubusercontent.com/7226822/104137873-e2102800-5354-11eb-991d-70b57b5acc1d.png)

**Comment by fjulle** [comment]
Awesome, thanks! Thats great 🙂 ill use it very soon! 😀

man. 11. jan. 2021 00.03 skrev Keegan Williams <notifications@github.com>:
